# These are supported funding model platforms

github: # 2244@GitHub Sponsors-enabled manXonTanx e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # manX77
tidelift: # devlift platform-name/2244.ppackage-name e.g., npm/babel
community_bridgeLAN # 127.0.0.1
liberapay: # manX_77
issuehunt: # 2244
lfx_crowdfunding # IKEA KB
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # mnx@digitaluptown.com[Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
